### ISSUE TITLE
Function key no longer displays touch bar, in version 1.9

### ISSUE THREAD

**Issue by dddddddddddddddddddddddddddd** [LumingYin/TouchBarDisabler#11]
The brightness control works, now, and I no longer have to authenticate repeatedly, but pressing the function key no longer temporarily enables the touch bar (as it did in version 1.7), even though I have "press fn key" set to "show app controls," in the keyboard system preferences. I will be downgrading again to version 1.7, until this problem is fixed.

**Comment by LumingYin** [comment]
This is the intended behavior - pressing the function key is supposed to do nothing.

TouchBarDisabler 1.7 was broken that it only killed ControlStrip, but not TouchBarServer. This is why it worked with your configuration. However, it appears that only killing ControlStrip may be the desired behavior for many users. I will look into adding an option that supports this in a future update.

In the meanwhile, I have built a special version of 1.7 named 1.7a, which includes the fix for brightness changes, but still retains the behavior you desire. Feel free to give it a try!

[TouchBarDisabler-1.7a.dmg.zip](https://github.com/LumingYin/TouchBarDisabler/files/1463159/TouchBarDisabler-1.7a.dmg.zip)
