### ISSUE TITLE
Some keyboard shortcuts do not work

### ISSUE THREAD

**Issue by viperabyss** [LumingYin/TouchBarDisabler#8]
After updating the Mac OS X to 10.13.1, the keyboard shortcuts for screen brightness (ctrl+1 / 2) no longer work. The rest of the shortcuts still work as usual.

**Comment by LumingYin** [comment]
If you update to version 1.9, the brightness control should behave as intended.

**[Download TouchBarDisabler 1.9 for macOS High Sierra](https://github.com/LumingYin/TouchBarDisabler/releases/download/1.9/TouchBarDisabler-1.9.dmg)**

**Comment by dddddddddddddddddddddddddddd** [comment]
The brightness control works, now, and I no longer have to authenticate repeatedly, but pressing the function key no longer temporarily enables the touch bar (as it did in version 1.7), even though I have "press fn key" set to "show app controls," in the keyboard system preferences. I will be downgrading again to version 1.7, until this problem is fixed.
